
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-injection-wujunwei-io-v1-sidecar
  failurePolicy: Fail
  name: msidecar.kb.io
  rules:
  - apiGroups:
    - injection.wujunwei.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sidecars

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-injection-wujunwei-io-v1-sidecar
  failurePolicy: Fail
  name: vsidecar.kb.io
  rules:
  - apiGroups:
    - injection.wujunwei.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sidecars
