apiVersion: injection.wujunwei.io/v1
kind: SideCar
metadata:
  namespace: default
  name: sidecar-sample
spec:
  # Add fields here
  retry_limit: 3
  toleration_duration: "5s"
  images:
    hello: busybox
  selector:
    matchLabels:
      app: hello