apiVersion: v1
kind: Namespace
metadata:
  labels:
    injection.wujunwei.io/inject: "true"
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginx:1.13.12
          ports:
            - containerPort: 80